import { Route, RouteIndexSummary, DailyIndex } from '@/types';

export const DGCA_ROUTE_BASKET: Route[] = [
  {
    id: 'DEL-BOM',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'BOM',
    destination_city: 'Mumbai',
    dgca_traffic_weight: 0.185,
    active: true,
    distance_km: 1148,
    daily_flights_avg: 74,
  },
  {
    id: 'BOM-DEL',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.178,
    active: true,
    distance_km: 1148,
    daily_flights_avg: 72,
  },
  {
    id: 'BLR-DEL',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.112,
    active: true,
    distance_km: 1740,
    daily_flights_avg: 48,
  },
  {
    id: 'DEL-BLR',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'BLR',
    destination_city: 'Bengaluru',
    dgca_traffic_weight: 0.109,
    active: true,
    distance_km: 1740,
    daily_flights_avg: 48,
  },
  {
    id: 'BOM-BLR',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'BLR',
    destination_city: 'Bengaluru',
    dgca_traffic_weight: 0.094,
    active: true,
    distance_km: 842,
    daily_flights_avg: 42,
  },
  {
    id: 'BLR-BOM',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'BOM',
    destination_city: 'Mumbai',
    dgca_traffic_weight: 0.091,
    active: true,
    distance_km: 842,
    daily_flights_avg: 41,
  },
  {
    id: 'DEL-CCU',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'CCU',
    destination_city: 'Kolkata',
    dgca_traffic_weight: 0.068,
    active: true,
    distance_km: 1305,
    daily_flights_avg: 32,
  },
  {
    id: 'CCU-DEL',
    origin_code: 'CCU',
    origin_city: 'Kolkata',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.065,
    active: true,
    distance_km: 1305,
    daily_flights_avg: 32,
  },
  {
    id: 'DEL-HYD',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'HYD',
    destination_city: 'Hyderabad',
    dgca_traffic_weight: 0.052,
    active: true,
    distance_km: 1253,
    daily_flights_avg: 28,
  },
  {
    id: 'BOM-MAA',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'MAA',
    destination_city: 'Chennai',
    dgca_traffic_weight: 0.046,
    active: true,
    distance_km: 1033,
    daily_flights_avg: 24,
  },
];

export const MOCK_ROUTE_SUMMARIES: RouteIndexSummary[] = [
  {
    route: DGCA_ROUTE_BASKET[0], // DEL-BOM
    representative_fare: 5450,
    t1_fare: 8900,
    t7_fare: 5800,
    t15_fare: 5100,
    t30_fare: 4400,
    t45_fare: 4100,
    delta_24h: 2.15,
    index_contribution: 19.82,
    carriers_sampled: ['6E', 'AI', 'QP', 'UK'],
    status: 'SURGE',
  },
  {
    route: DGCA_ROUTE_BASKET[1], // BOM-DEL
    representative_fare: 5320,
    t1_fare: 8650,
    t7_fare: 5600,
    t15_fare: 4950,
    t30_fare: 4350,
    t45_fare: 4050,
    delta_24h: 1.80,
    index_contribution: 18.64,
    carriers_sampled: ['6E', 'AI', 'QP', 'UK'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[2], // BLR-DEL
    representative_fare: 6850,
    t1_fare: 11200,
    t7_fare: 7400,
    t15_fare: 6400,
    t30_fare: 5800,
    t45_fare: 5400,
    delta_24h: -1.20,
    index_contribution: 12.10,
    carriers_sampled: ['6E', 'AI', 'IX'],
    status: 'EASED',
  },
  {
    route: DGCA_ROUTE_BASKET[3], // DEL-BLR
    representative_fare: 6920,
    t1_fare: 11500,
    t7_fare: 7550,
    t15_fare: 6500,
    t30_fare: 5850,
    t45_fare: 5450,
    delta_24h: 0.45,
    index_contribution: 11.95,
    carriers_sampled: ['6E', 'AI', 'IX'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[4], // BOM-BLR
    representative_fare: 4150,
    t1_fare: 6800,
    t7_fare: 4400,
    t15_fare: 3900,
    t30_fare: 3450,
    t45_fare: 3200,
    delta_24h: -0.65,
    index_contribution: 9.20,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'STABLE',
  },
  {
    route: DGCA_ROUTE_BASKET[5], // BLR-BOM
    representative_fare: 4200,
    t1_fare: 6950,
    t7_fare: 4500,
    t15_fare: 3950,
    t30_fare: 3500,
    t45_fare: 3250,
    delta_24h: 1.10,
    index_contribution: 9.05,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[6], // DEL-CCU
    representative_fare: 5850,
    t1_fare: 9800,
    t7_fare: 6200,
    t15_fare: 5400,
    t30_fare: 4800,
    t45_fare: 4500,
    delta_24h: 3.40,
    index_contribution: 7.35,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'SURGE',
  },
  {
    route: DGCA_ROUTE_BASKET[7], // CCU-DEL
    representative_fare: 5700,
    t1_fare: 9400,
    t7_fare: 6050,
    t15_fare: 5300,
    t30_fare: 4750,
    t45_fare: 4450,
    delta_24h: 2.10,
    index_contribution: 6.98,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[8], // DEL-HYD
    representative_fare: 5200,
    t1_fare: 8400,
    t7_fare: 5500,
    t15_fare: 4850,
    t30_fare: 4250,
    t45_fare: 3950,
    delta_24h: -1.85,
    index_contribution: 5.10,
    carriers_sampled: ['6E', 'AI'],
    status: 'EASED',
  },
  {
    route: DGCA_ROUTE_BASKET[9], // BOM-MAA
    representative_fare: 4750,
    t1_fare: 7600,
    t7_fare: 5000,
    t15_fare: 4450,
    t30_fare: 3900,
    t45_fare: 3600,
    delta_24h: 0.15,
    index_contribution: 4.55,
    carriers_sampled: ['6E', 'AI'],
    status: 'STABLE',
  },
];

export const CURRENT_LIVE_INDEX: DailyIndex = {
  id: 'idx-2026-08-22',
  index_date: '2026-08-22',
  frequency: 'daily',
  apix_value: 104.82,
  base_period_value: 100.0,
  delta_24h: 1.42,
  delta_7d: 3.18,
  delta_30d: -0.95,
  median_basket_fare: 5450,
  weighted_basket_fare: 5612,
  active_routes_count: 10,
  records_processed: 1420,
  methodology_notes: 'Laspeyres-style weighted by DGCA 2025/2026 passenger shares across T+1..T+45 windows',
};
