import { Route, RouteIndexSummary, DailyIndex } from '@/types';

export const DGCA_ROUTE_BASKET: Route[] = [
  {
    id: 'DEL-BOM',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'BOM',
    destination_city: 'Mumbai',
    dgca_traffic_weight: 0.155,
    active: true,
    distance_km: 1148,
    daily_flights_avg: 74,
  },
  {
    id: 'BOM-DEL',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.145,
    active: true,
    distance_km: 1148,
    daily_flights_avg: 72,
  },
  {
    id: 'DEL-BLR',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'BLR',
    destination_city: 'Bengaluru',
    dgca_traffic_weight: 0.095,
    active: true,
    distance_km: 1740,
    daily_flights_avg: 52,
  },
  {
    id: 'BLR-DEL',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.090,
    active: true,
    distance_km: 1740,
    daily_flights_avg: 51,
  },
  {
    id: 'BOM-BLR',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'BLR',
    destination_city: 'Bengaluru',
    dgca_traffic_weight: 0.078,
    active: true,
    distance_km: 842,
    daily_flights_avg: 42,
  },
  {
    id: 'BLR-BOM',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'BOM',
    destination_city: 'Mumbai',
    dgca_traffic_weight: 0.075,
    active: true,
    distance_km: 842,
    daily_flights_avg: 41,
  },
  {
    id: 'DEL-CCU',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'CCU',
    destination_city: 'Kolkata',
    dgca_traffic_weight: 0.058,
    active: true,
    distance_km: 1305,
    daily_flights_avg: 32,
  },
  {
    id: 'CCU-DEL',
    origin_code: 'CCU',
    origin_city: 'Kolkata',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.055,
    active: true,
    distance_km: 1305,
    daily_flights_avg: 31,
  },
  {
    id: 'BLR-HYD',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'HYD',
    destination_city: 'Hyderabad',
    dgca_traffic_weight: 0.040,
    active: true,
    distance_km: 500,
    daily_flights_avg: 28,
  },
  {
    id: 'MAA-DEL',
    origin_code: 'MAA',
    origin_city: 'Chennai',
    destination_code: 'DEL',
    destination_city: 'Delhi',
    dgca_traffic_weight: 0.034,
    active: true,
    distance_km: 1760,
    daily_flights_avg: 24,
  },
  {
    id: 'DEL-GAU',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'GAU',
    destination_city: 'Guwahati',
    dgca_traffic_weight: 0.035,
    active: true,
    distance_km: 1460,
    daily_flights_avg: 18,
  },
  {
    id: 'BOM-GOI',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'GOI',
    destination_city: 'Goa',
    dgca_traffic_weight: 0.032,
    active: true,
    distance_km: 435,
    daily_flights_avg: 22,
  },
  {
    id: 'DEL-PAT',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'PAT',
    destination_city: 'Patna',
    dgca_traffic_weight: 0.038,
    active: true,
    distance_km: 850,
    daily_flights_avg: 20,
  },
  {
    id: 'BLR-COK',
    origin_code: 'BLR',
    origin_city: 'Bengaluru',
    destination_code: 'COK',
    destination_city: 'Kochi',
    dgca_traffic_weight: 0.028,
    active: true,
    distance_km: 367,
    daily_flights_avg: 16,
  },
  {
    id: 'DEL-IXC',
    origin_code: 'DEL',
    origin_city: 'Delhi',
    destination_code: 'IXC',
    destination_city: 'Chandigarh',
    dgca_traffic_weight: 0.022,
    active: true,
    distance_km: 235,
    daily_flights_avg: 14,
  },
  {
    id: 'BOM-PNQ',
    origin_code: 'BOM',
    origin_city: 'Mumbai',
    destination_code: 'PNQ',
    destination_city: 'Pune',
    dgca_traffic_weight: 0.020,
    active: true,
    distance_km: 120,
    daily_flights_avg: 12,
  },
];

export const MOCK_ROUTE_SUMMARIES: RouteIndexSummary[] = [
  {
    route: DGCA_ROUTE_BASKET[0], // DEL-BOM
    representative_fare: 5450,
    t1_fare: 8900,
    t7_fare: 6200,
    t15_fare: 5450,
    t30_fare: 4600,
    t45_fare: 4100,
    delta_24h: 2.1,
    index_contribution: 1008.25,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'SURGE',
  },
  {
    route: DGCA_ROUTE_BASKET[1], // BOM-DEL
    representative_fare: 5380,
    t1_fare: 8750,
    t7_fare: 6100,
    t15_fare: 5380,
    t30_fare: 4550,
    t45_fare: 4050,
    delta_24h: 1.8,
    index_contribution: 957.64,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[2], // DEL-BLR
    representative_fare: 6850,
    t1_fare: 11200,
    t7_fare: 7900,
    t15_fare: 6850,
    t30_fare: 5800,
    t45_fare: 5200,
    delta_24h: -1.2,
    index_contribution: 767.2,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'EASED',
  },
  {
    route: DGCA_ROUTE_BASKET[3], // BLR-DEL
    representative_fare: 6790,
    t1_fare: 10950,
    t7_fare: 7800,
    t15_fare: 6790,
    t30_fare: 5750,
    t45_fare: 5150,
    delta_24h: 0.4,
    index_contribution: 740.11,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'STABLE',
  },
  {
    route: DGCA_ROUTE_BASKET[4], // BOM-BLR
    representative_fare: 4250,
    t1_fare: 6900,
    t7_fare: 4900,
    t15_fare: 4250,
    t30_fare: 3600,
    t45_fare: 3200,
    delta_24h: 3.4,
    index_contribution: 399.5,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'SURGE',
  },
  {
    route: DGCA_ROUTE_BASKET[5], // BLR-BOM
    representative_fare: 4180,
    t1_fare: 6750,
    t7_fare: 4800,
    t15_fare: 4180,
    t30_fare: 3550,
    t45_fare: 3150,
    delta_24h: -0.8,
    index_contribution: 380.38,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[6], // DEL-CCU
    representative_fare: 5950,
    t1_fare: 9600,
    t7_fare: 6850,
    t15_fare: 5950,
    t30_fare: 5100,
    t45_fare: 4500,
    delta_24h: 1.1,
    index_contribution: 404.6,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'NORMAL',
  },
  {
    route: DGCA_ROUTE_BASKET[7], // CCU-DEL
    representative_fare: 5880,
    t1_fare: 9450,
    t7_fare: 6750,
    t15_fare: 5880,
    t30_fare: 5050,
    t45_fare: 4450,
    delta_24h: 0.2,
    index_contribution: 382.2,
    carriers_sampled: ['6E', 'AI'],
    status: 'STABLE',
  },
  {
    route: DGCA_ROUTE_BASKET[8], // BLR-HYD
    representative_fare: 3650,
    t1_fare: 5900,
    t7_fare: 4200,
    t15_fare: 3650,
    t30_fare: 3100,
    t45_fare: 2750,
    delta_24h: 2.8,
    index_contribution: 189.8,
    carriers_sampled: ['6E', 'AI', 'QP'],
    status: 'SURGE',
  },
  {
    route: DGCA_ROUTE_BASKET[9], // MAA-DEL
    representative_fare: 6950,
    t1_fare: 11400,
    t7_fare: 8050,
    t15_fare: 6950,
    t30_fare: 5900,
    t45_fare: 5300,
    delta_24h: -1.5,
    index_contribution: 319.7,
    carriers_sampled: ['6E', 'AI', 'SG'],
    status: 'EASED',
  },
];

export const CURRENT_LIVE_INDEX: DailyIndex = {
  id: 'daily_index_2026-08-24',
  index_date: '2026-08-24',
  frequency: 'daily',
  apix_value: 186.65,
  base_period_value: 100.0,
  delta_24h: 30.33,
  delta_7d: 1.45,
  delta_30d: 5.83,
  median_basket_fare: 5280,
  weighted_basket_fare: 9855.12,
  active_routes_count: 16,
  records_processed: 45006,
  distinct_dates_count: 2,
  collected_dates: ['2026-08-22', '2026-08-24'],
  methodology_notes:
    'Methodology: Laspeyres Weighted Basket Index (MoSPI CPI Transport Sub-Group Augmentation) | Base Period Value: 100.00 (Jan 2026 Reference Basket Fare = ₹5280.00) | Current 24h Weighted Basket Fare: ₹9855.12 | Active Corridors Sampled: 16/16 DGCA routes (Trunk + Tier-2) | Total Flight Quotes Evaluated: 45,006 (3,579 outliers rejected via Tukey IQR)',
};
